### ISSUE TITLE
Rename Project to CosmosDB SQL

### ISSUE THREAD

**Issue by brunoborges** [Azure/azure-documentdb-java#100]
Hi team,

Azure DocumentDB is now Azure CosmosDB SQL. Are there plans to rename this project accordingly?

https://azure.microsoft.com/en-us/blog/dear-documentdb-customers-welcome-to-azure-cosmos-db/

**Comment by moderakh** [comment]
@brunoborges thanks for the comment.

We have a cosmos db java SDK. Please check it here:
https://github.com/Azure/azure-cosmosdb-java
