### ISSUE TITLE
SDK github url 

### ISSUE THREAD

**Issue by prashanthmadi** [Azure/azure-documentdb-java#108]
Is this SDK or just samples ?

Below link says this repo as SDK but i just see only samples/benchmarking here...
https://docs.microsoft.com/en-us/azure/cosmos-db/sql-api-sdk-java

Can you list SDK url in readme and also set it as homepage in mvn repo too
https://mvnrepository.com/artifact/com.microsoft.azure/azure-documentdb/1.16.0

**Comment by prashanthmadi** [comment]
Thanks @moderakh .. whats the sync sdk url ?

**Comment by moderakh** [comment]
at this point only source for async sdk is available. the source for sync sdk is not available.
As you yourself pointed out this repo only has example/benchmarking tool.
