### ISSUE TITLE
ignore model property while saving record in documentdb

### ISSUE THREAD

**Issue by dixitprashant444** [Azure/azure-documentdb-java#122]
I have a class:
public class Job
{
     private String id;
     private String type;
     private boolean history;
}
I want to ignore "history" property while saving the record in collection.
I tried @JsonIgnore but this does not work. I can see "history": false in saved record inside document db.
I do not want "history" attribute inside my saved record/document.
We have @DynamoDBIgnore for Amazon dynamo db. Can you please suggest the work around for your SDK?

**Comment by ealsur** [comment]
@dixitprashant444 We have tested this scenario and found that JsonIgnore does work. Do you have any repro code that you can share with us?

**Comment by dixitprashant444** [comment]
@ealsur Lombok annotation was preventing JsonIgnore to work properly. See this https://github.com/FasterXML/jackson-databind/issues/1226
When I removed lombok annotations from my model class & wrote getters, setters & constructors then JsonIgnore started working.
Thanks for quick reply & confirmation that this was not an issue from your end.
