### ISSUE TITLE
Android Compatibilty

### ISSUE THREAD

**Issue by jdscolam** [Azure/azure-documentdb-java#13]
Hi,

I am trying to use the documentdb library from android, and it doesn't seem to be compatible.  I've spent the past few hours googling the issue (which seems to be the version of Apache's httpclient used), however I am at a loss on how to get the right version of the dependencies.

As an FYI I am using the latest version of android studio, targeting the latest version of android.

Do you have any thoughts or suggestions?

The error I am getting is as follows:  java.lang.ClassNotFoundException: Didn't find class "org.apache.http.impl.conn.PoolingClientConnectionManager" on path: DexPathList[[zip file "/data/app/com.example.mydir.myproj-1/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]

Thanks in advance!

-Jon

**Comment by aliuy** [comment]
The DocumentDB Java Client doesn't officially support Android just *yet*.

That being said - I have heard from some other users that they were able to get it working. If I remember correctly, the steps are to pull down the DocumentDB Java Client source code and make the following edits:

* Comment out the PoolingClientConnectionManager in GatewayProxy.java
* Base64.encodeBase64String in Helper.java is the method failing in run time on Android (Android Runtime: java.lang.NoSuchMethodError)... Change "encodeBase64String()" to "new String(encodeBase64())"

I don't have an the Android SDK and phone set up - so I haven't tested this myself.

If you happen to get it working - I'd be very grateful for a pull-request :wink:

**Comment by jdscolam** [comment]
Thanks for the response!  I might give that a try here later.  In the meantime I used Retrofit and the REST API to get it working.  That was nine hours worth of pain, but the working result is here:  http://stackoverflow.com/questions/28654821/connect-to-azure-documentdb-from-android

It isn't perfect, but it works for now.  I think I'd prefer to use the "official" client in the future as it would make my life easier :).

**Comment by rnagpal** [comment]
@jdscolam Let us know if you still need this feature, otherwise I'll close his issue as this has been open since 2 years now.

**Comment by gondooley** [comment]
Close away. Not concerned any more.
Thank,
Reg.

**Comment by jdscolam** [comment]
Is there an Android client for the SDK now?
