### ISSUE TITLE
PopulateQueryMetrics in FeedOptions

### ISSUE THREAD

**Issue by sheekaat** [Azure/azure-documentdb-java#131]
Trying to see the usage of Indexes utilization percentage and observed that this parameter is in .NET SDK API. But, not in the Java SDK API.

**Comment by ealsur** [comment]
PopulateQueryMetrics is available in the 2.4.X version of [Java Async SDK](https://github.com/Azure/azure-cosmosdb-java). For the Sync SDK, it's targeted for 3.0 release.
