### ISSUE TITLE
JsonSerializable "c must be a member (not an anonymous or local) and static class."

### ISSUE THREAD

**Issue by wjobin** [Azure/azure-documentdb-java#16]
IMO, forcing inner class for POJO mapping is wrong. Should be "inner class must be static".

I changed the condition on JsonSerializable.java:437 to `c.isMemberClass() && !Modifier.isStatic(c.getModifiers())` on my side and it works as expected.

I'd suggest changing all the alike conditions in the JsonSerializable.java.

William

**Comment by ryancrawcour** [comment]
Thanks for raising this, We will investigate. Alternatively, we would be more than happy to accept a PR from you to address this issue.

**Comment by shipunyc** [comment]
Thanks. I fixed this bug with a commit just now. The next release will include this fix.
