### ISSUE TITLE
tutorial pom.xml isn't enough for building apps?

### ISSUE THREAD

**Issue by normalian** [Azure/azure-documentdb-java#29]
I cloned tutorial apps from github and run "mvn eclipse:eclipse" using https://github.com/Azure/azure-documentdb-java/blob/master/tutorial/todo/pom.xml. But i got "The import javax.servlet cannot be resolved" error.

I guess the pom.xml needs "servlet-api" for building apps, is this right?

**Comment by aliuy** [comment]
`javax.servlet` comes installed with the Java EE (Enterprise Edition) SDK, which can be downloaded [here](http://www.oracle.com/technetwork/java/javaee/downloads/index.html)

**Comment by aliuy** [comment]
I haven't tried the `servlet-api` maven artifact, but perhaps that works too.

If you go down this route, mind posting back here with your results?

**Comment by normalian** [comment]
I have already tried to non 'servlet-api' pom.xml, but it didn't work. And sorry aliuy, I have already merged servlet-api to pom.xml in pull request #30. 
https://github.com/Azure/azure-documentdb-java/blob/master/tutorial/todo/pom.xml

If it will cause some troubles, please remove it.
