### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by wjobin** [Azure/azure-documentdb-java#33]
Hey,

Could you make a new release? I'd like to switch back to official release before going in prod, but I need the fixes I made in June.

Thanks

**Comment by ryancrawcour** [comment]
Sure, we have a release planned for later in the week

**Comment by wjobin** [comment]
Excellent thanks

**Comment by ryancrawcour** [comment]
just checked, the release will be next week. if you're able to wait until then all good, else I can push a new version out with just these fixes.

**Comment by wjobin** [comment]
Next week is fine.
