### ISSUE TITLE
SSLHandshakeException ValidatorException: PKIX path building failed

### ISSUE THREAD

**Issue by boly38** [Azure/azure-documentdb-java#44]
Hi
Since few days in some tests executions I encounter SSL validation errror while querying documentdb.
   (cf detailled stack trace into attached file)
[SSLHandshakeExceptionValidatorExceptionPKIX.stack.txt](https://github.com/Azure/azure-documentdb-java/files/227883/SSLHandshakeExceptionValidatorExceptionPKIX.stack.txt)

    java.lang.IllegalStateException: Exception not retriable
    Caused by: java.lang.IllegalStateException: Http client execution failed.
        	at com.microsoft.azure.documentdb.GatewayProxy.performPostRequest(GatewayProxy.java:388)
    Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
    Caused by: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

This issue is not easy to reproduce on my side because sometime same tests are OK and sometime 2, 3, N of this tests are throwing this error.

I take an end-of-march Release of my product to replay the same QA Tests Sets and I encounter this issue. Release tests were all OK at end-of-march!

My continuous integration server is on an Azure VM so there is no proxy configuration. And related DocumentDB account endpoint return a valid certificate following my browser check. There is no update or change (for example of the java keystore) of the JRE on my continuous integration server.

"azure-documentdb" version 1.6.0 library rely on apache http client which seems using default TLS context SSL socket factory. So why do I get this error ?

Does anybody encounter this error ?  Do you have a way to fix it ?

Is it possible that in some case Azure DocumentDB frontend redirect my query to an invalid https endpoint ? out of DNS outage yesterday, Azure doesn't report related outage in the [status page](https://azure.microsoft.com/en-us/status/#history)

Regards

**Comment by shellygms** [comment]
Hi, there was no change in the networking layer for version 1.6.0, so to help with diagnostic, could you try reverting back to 1.5.1 and see if you can repro this problem?

Thanks.

**Comment by shellygms** [comment]
Hi, one reason you could encounter this error is when the root CA is missing on your system.  A few things you can do to help diagnose the problem.
1. Go to Chrome and browse to your documentdb root url using https.  Check if you encounter a certificate error or warning.  There should be a green lock before your url if everything is working correct.  Click on the lock should show you the certificate info.  Our cert is rooted to the Baltimore CyberTrust room.
2. Make sure the root cert is in your root CA store.  Different OS manages CA stores differently so you need to following procedures for your target OS.
3. Make sure the root cert is in your JRE root CA store.  This is typically located at: "%JAVA_HOME%/jre/lib/security/cacerts".

Thanks.

**Comment by boly38** [comment]
(FYI / I'm currently discussing with Azure Support team so I will update this thread as soon as I found the fix)

**Comment by rnagpal** [comment]
This issue has been fixed in Java SDK release 1.7.1.
