### ISSUE TITLE
DocumentClient.upsertStoredProcedure(): "One of the specified inputs is invalid" (1.7.1)

### ISSUE THREAD

**Issue by mparker** [Azure/azure-documentdb-java#49]
I'm calling DocumentClient.upsertStoredProcedure() like this:

`           String s = ...; // body of stored procedure, copied from the azure console script explorer
            StoredProcedure sp = new StoredProcedure();
            sp.setBody(s);
            getDocumentClient().upsertStoredProcedure(c.getSelfLink(), sp, null);
 `

Since the javadocs for StoredProcedure and DocumentClient don't specify how the content should be formatted (other than 'json'), for the 'body of stored procedure', I've tried using both the javascript function body by itself (`"function foo() ..."`) and also the json payload (`{ "id": "...", "body": "function foo() ..." }`). Both attempts result in `com.microsoft.azure.documentdb.DocumentClientException: Message: {"Errors":["One of the specified inputs is invalid"]}`. I first validated that the function was defined correctly by writing it inside the azure console script explorer, and executing it successfully, and am now trying to define it in my code. I am also making sure to properly escape the quote characters inside the body, since it's now defined in java.

**Comment by shellygms** [comment]
Hi, the following is a code snippet for upsertStoredProcedure()

        StoredProcedure storedProcedureDefinition = new StoredProcedure();
        storedProcedureDefinition.setId("proc1");
        storedProcedureDefinition.setBody("function() {var x = 10;}");

        StoredProcedure createdStoredProcedure = documentClient.upsertStoredProcedure(
                collectionLink,
                storedProcedureDefinition, null).getResource();

Let me know if that helps.

**Comment by mparker** [comment]
Thanks Shelly, that helped. I didn't notice that setId() was inherited from Resource, or that it was required.
