### ISSUE TITLE
bulk insert and bulk delete for azure documentdb

### ISSUE THREAD

**Issue by jonathanlinadv** [Azure/azure-documentdb-java#61]
Can anyone give some samples for bulk insert and bulk delete in JAVA?

**Comment by kiratp** [comment]
https://github.com/Azure/azure-documentdb-dotnet/tree/master/samples/clientside-transactions/DocDBClientBulk/DocDBClientBulk

The server side code (JS files) will be the same - you would just call it with the Java client.

Also, you can use TTL to bulk delete without incurring any RU charges: https://azure.microsoft.com/en-us/documentation/articles/documentdb-time-to-live/

**Comment by jonathanlinadv** [comment]
Thanks for your help. That's very good.
I have more questions.
How to call it (the server side code (JS files)) with JAVA client?
How to transfer the parameters into it (the server side code (JS files)) in back-end JAVA?
May you provide some samples?

**Comment by kiratp** [comment]
https://docs.microsoft.com/en-us/azure/documentdb/documentdb-programming#a-idudfauser-defined-functions

**Comment by jonathanlinadv** [comment]
Thank you. But, it is not the JAVA codes.
I will try it.

**Comment by anoopprk** [comment]
For an array of com.microsoft.azure.documentdb.Document objects, you can create an Array<String> by calling toString on each object. This array of Strings can be passed as a parameter to the stored procedure like so:
response = client.executeStoredProcedure(sproc.getSelfLink(), new Object[] { jsonArrayString, upsert })
.getResponseAsString();

This worked fine for me in java. You can refer to the documentDB Hadoop connector code which seems to be doing the same thing behind the scenes:
https://github.com/Azure/azure-documentdb-hadoop/blob/35a7bde8201d816ee278fea53583ae3f4bf8e341/src/com/microsoft/azure/documentdb/hadoop/DocumentDBConnectorUtil.java#L218

**Comment by rnagpal** [comment]
@jonathanlinadv Let us know if you still need help with the sample, otherwise I'll close this issue.
