### ISSUE TITLE
1.8.1 Version Updated In Maven Central After Initial Release (Contains a Bug)

### ISSUE THREAD

**Issue by Blackbaud-MitchellThomas** [Azure/azure-documentdb-java#62]
We discovered through failing tests that the 1.8.1 artifact was updated in Maven Central without an appropriate version increment. We discovered this this through a bug in `queryDatabases` that also exists in 1.9.0, which my team will file as a separate issue. We didn't discover the issue until we built in an environment that didn't have the original 1.8.1 version cached.

As near as we can tell, the artifact published at the URL below is the original version. It was uploaded Jun 30th, 2016.

http://mvnrepository.com/artifact/com.microsoft.azure/azure-documentdb/1.8.1

But the Maven Central artifact published at the URL below was updated Sept. 23rd, 2016 and contains the bug.

http://search.maven.org/#artifactdetails%7Ccom.microsoft.azure%7Cazure-documentdb%7C1.8.1%7Cjar

We either have to work around this bug in our code or push a copy of the one that works into our Maven repository and quit pulling the Maven Central version.

**Comment by khdang** [comment]
Thanks for letting us know @Blackbaud-MitchellThomas. We're looking into restoring the original 1.8.1 version on Maven repository. For the issue with queryDatabases, please file a bug and we will fix it in the next release.

**Comment by Blackbaud-MitchellThomas** [comment]
Sounds good. Thanks. I also discovered that the Sept. 23rd version will block my triggers after a few runs on my test suite for violating resource limits. 1.9.0 appears to have that bug fixed, though.

**Comment by khdang** [comment]
@Blackbaud-MitchellThomas We've restored 1.8.1 to the version on June 30th. Let us know if you're still having the bug.

**Comment by Blackbaud-MitchellThomas** [comment]
The 1.8.1 version I pulled from Maven no longer contains the bug.
