### ISSUE TITLE
DocumentClient queryDatabases Ignores the Query

### ISSUE THREAD

**Issue by Blackbaud-MitchellThomas** [Azure/azure-documentdb-java#63]
No matter what query you provide to the `queryDatabases` function, it returns all databases.

I believe it is related to this line:

https://github.com/Azure/azure-documentdb-java/blob/879912d323777aac57b675039159f3ab8f8efb85/src/com/microsoft/azure/documentdb/DocumentClient.java#L437

The constructor that it calls doesn't take in a `SqlQuerySpec`, so `querySpec` is just dropped on the floor.

I was going to make a very simple PR, but I don't have the time at present to get the SDK building on my machine if that's all the issue is.

**Comment by khdang** [comment]
@Blackbaud-MitchellThomas Thanks for the details. We're aware of this issue and will have it fixed in the coming release.

**Comment by Blackbaud-MitchellThomas** [comment]
Thanks, @khdang.

**Comment by Blackbaud-IanThomas** [comment]
Do you have an estimate of when the next release will be available?  Will it be a 1.9.1 release coming quickly?

**Comment by khdang** [comment]
@Blackbaud-IanThomas We're actively working on the Java SDK to improve the experience to use Azure DocumentDB service. We will release new version when they are ready. If you have any issues or requests please let us know we will get to it as soon as we can.
