### ISSUE TITLE
Where is the latest code? Public artifacts are version 1.9.x, but repo is still 1.8.x

### ISSUE THREAD

**Issue by al3xandru** [Azure/azure-documentdb-java#69]
Hi,

I wanted to submit a very minor PR against 1.9.6 version which seems to be the latest available in Maven central, but it looks like the repo here is still at 1.8.x.

_2 seconds later update: for whatever reasons I haven't noticed the disclaimer in the readme._

**Comment by apatrida** [comment]
This is still a problem not having current source for the release.

**Comment by ZhijunZhao** [comment]
Yes. This wasted me a lot of time. The source code here is not consistent with the latest public artifacts...

**Comment by khdang** [comment]
As noted in the Disclaimer in the README section, the current code in this repo is a reference implementation. Due to reasons that cannot be disclosed, we currently don't publish the latest source code but we're planning to as soon as we can.
