### ISSUE TITLE
it's time to rename the repo to azure-cosmosdb-java 

### ISSUE THREAD

**Issue by SychevIgor** [Azure/azure-documentdb-java#74]
Because we had renamed documentDB to cosmosDB - it will be right if we will update the repo name as well.

**Comment by khdang** [comment]
The SDK provides the DocumetDB APIs which is a subset of the new Azure CosmosDB APIs. For more details, you can check out this link:  https://docs.microsoft.com/en-us/azure/cosmos-db/documentdb-introduction.
