### ISSUE TITLE
InterruptedException when reading Databases

### ISSUE THREAD

**Issue by AnaCampoVe** [Azure/azure-documentdb-java#77]
Hi team!!!

We are integrating DocumentDb in our java project. For that purpose, we have created a static class that performs the operations through the DocumentClient. Sometimes, when we try to read the Databases in our init method, we get a chained exception -> IllegalStateException-DocumentClientException-InterruptedException.

This is our piece of code:

```
private static ConnectionPolicy connectionPolicy;
private static DocumentClient client;
private static Database db;
public synchronized static void init() {
        if (db == null) {
            connectionPolicy = new ConnectionPolicy();
            connectionPolicy.setConnectionMode(ConnectionMode.DirectHttps);

            client = new DocumentClient(serviceEndpoint, masterKey,
                connectionPolicy, ConsistencyLevel.Session);

            FeedResponse<Database> clientResponse = client.readDatabases(null);
            List<Database> dbList = clientResponse.getQueryIterable().toList();

            db = dbList
                    .stream()
                    .filter(d -> d.getId().equals(databaseName))
                    .findFirst()
                    .get();
        }
    }
```

Do you know which could be the cause of this exception??? We can debug it til RetryUtility.class. The exception is thrown in RetryRequestDelegate.apply, but as the class is internal, we cannot step into that code.

**Comment by khdang** [comment]
@AnaCampoVe since you're reading database by database name, you can use readDatabase API with the database named link ("dbs/" + databaseName). 

If you're still seeing this issue, can you please provide us with the full stack trace? Also, let us know if you're seeing this in a consistent manner at a specific time frame of the application?

**Comment by khdang** [comment]
I'm closing this for now. Please feel free to reopen if you're still having any issues.
