### ISSUE TITLE
upsertDocument not working

### ISSUE THREAD

**Issue by dluc** [Azure/azure-documentdb-java#78]
I'm trying to figure out if the `upsertDocument` method works. So far I've been unable to get the code below to work. 

I need to set the document Id, so I'm using `disableAutomaticIdGeneration = true` (if I change it to `false` the first code snippet below works, but that's not my scenario)

Using version: 1.12.0

Fails with "StatusCode: BadRequest - One of the specified inputs is invalid":

```scala
// data to store (partition and offset are data in my app, nothing to do with DocDb partitions)
val data = Map("id" → s"partition$partition", "partition" → partition, "offset" → offset)
client.upsertDocument(s"/dbs/$dbName/colls/$collName/", data, null, true)
```

Fails with "RequestHandler.Post, StatusCode: MethodNotAllowed":

```scala
// data to store (partition and offset are data in my app, nothing to do with DocDb partitions)
val data = Map("id" → s"partition$partition", "partition" → partition, "offset" → offset)
client.upsertDocument(s"/dbs/$dbName/colls/$collName/docs/", data, null, true)
```

Fails with "StatusCode: BadRequest - Request url is invalid":

```scala
// data to store (partition and offset are data in my app, nothing to do with DocDb partitions)
val data = Map("id" → s"partition$partition", "partition" → partition, "offset" → offset)
client.upsertDocument(s"/dbs/$dbName/colls/$collName/docs/partition$partition", data, null, true)
```

**Comment by khdang** [comment]
@dluc the upsertDocument API takes collection link as the 1st parameter. If you're using namebased link it's in the format of "dbs/$dbName/colls/$collName" (without the '/' at the beginning).

For more samples you can take a look at the unit tests:
https://github.com/Azure/azure-documentdb-java/blob/93cb237f97b1f0c1138278211835ccf8144452bc/test/com/microsoft/azure/documentdb/GatewayTests.java#L760
https://github.com/Azure/azure-documentdb-java/blob/93cb237f97b1f0c1138278211835ccf8144452bc/test/com/microsoft/azure/documentdb/GatewayTestBase.java#L257

**Comment by dluc** [comment]
@khdang Thanks. I'd suggest to either improve the input validation or be more flexible and handle these edge cases, e.g. trimming the string where needed.
