### ISSUE TITLE
Add support for custom ObjectMapper in DocumentClient

### ISSUE THREAD

**Issue by qwazer** [Azure/azure-documentdb-java#85]
In azure-documentdb-1.13.0.jar objectMapper is not configurable and created for ***every*** save operation

decompiled code:
````
 private static String serializeProcedureParams(Object[] objectArray) {
        ObjectMapper mapper = null;
        String[] stringArray = new String[objectArray.length];

        for(int i = 0; i < objectArray.length; ++i) {
            Object object = objectArray[i];
            if (object instanceof JsonSerializable) {
                stringArray[i] = ((JsonSerializable)object).toJson();
            } else if (object instanceof JSONObject) {
                stringArray[i] = object.toString();
            } else {
                if (mapper == null) {
                    mapper = new ObjectMapper();
                }

                try {
                    stringArray[i] = mapper.writeValueAsString(object);
                } catch (IOException var6) {
                    throw new IllegalArgumentException("Can't serialize the object into the json string", var6);
                }
            }
        }

        return String.format("[%s]", StringUtils.join(stringArray, ","));
    }
`````

Please fix performance issue and add ability to use custom object mapper

**Comment by kirankumarkolli** [comment]
+1 Assigned to @moderakh

**Comment by moderakh** [comment]
The fix for not recreating ObjectMapper will be in the next release of java sdk coming out this week.

**Comment by moderakh** [comment]
@qwazer please check 1.15.0 release which has the fix.

**Comment by qwazer** [comment]
there is no support for custom object mapper in 1.15.0

**Comment by qwazer** [comment]
please reopen

**Comment by moderakh** [comment]
@qwazer Please check the constructor of DocumentClient. The main purpose of the fix was to fix the performance issue. But there is a new constructor through which you can pass the custom ObjectMapper.

**Comment by moderakh** [comment]
@qwazer as mentioned there is a new constructor for passing custom mapper. If you find problem with custom serialization feel free to open a new issue.

**Comment by qwazer** [comment]
ok thanks 
I missed new Constructor in decompiled code
