### ISSUE TITLE
Azure document db java SDK bulk insert and bulk delete

### ISSUE THREAD

**Issue by aqua-regia** [Azure/azure-documentdb-java#87]
1)Given a List of Documents  what is the most efficient way to insert them into Document-DB using Java SDK? Is stored procedure the only way.
I don't want to traverse over each and then use the createDocument method.

2)Given List of String containing  _self links,  how can I delete all the documents that correspond to the _self?

**Comment by moderakh** [comment]
1) @aqua-regia the most efficient way is to import using stored proc assuming the documents have the same partition key. 
2) You can traverse over the list of documents and deleting one by one.
