### ISSUE TITLE
DocumentClient should not log serviceEndpoint with credential information

### ISSUE THREAD

**Issue by zhang-hua** [Azure/azure-documentdb-java#92]
```
com.microsoft.azure\azure-documentdb\jars\azure-documentdb-1.12.0.jar!\com\microsoft\azure\documentdb\DocumentClient.java

 private void initialize(URI serviceEndpoint, ConnectionPolicy connectionPolicy, ConsistencyLevel desiredConsistencyLevel, UserAgentContainer userAgentContainer) {
        logger.info("Initializing DocumentClient with serviceEndpoint [{}], ConnectionPolicy [{}], ConsistencyLevel [{}]", new Object[]{serviceEndpoint, connectionPolicy, desiredConsistencyLevel});
```

**Comment by moderakh** [comment]
@zhang-hua could you please be more elaborate. Only masterKey is credential, which is not logged. Service endpoint does not contain credential information.

**Comment by zhang-hua** [comment]
@moderakh , I found the DocumentClient can accept service endpoint like below:
```
https://xxxx-xxxx.documents.azure.com:443/;AccountKey=xxxxxxxxxx==
```
It is a legal URI with `AccountKey` which is appended at the end of actual endpoint string and can be used in DocumentClient constructor. Client code should not pass this kind of connection string to create DocumentClient instance. It might be safer to filter it before logging this info. Don't know if this will leak the account key when sending  request at the beginning of HTTPS session.

**Comment by moderakh** [comment]
@zhang-hua I am trying to understand what the concern is.

The DocumentClient constructor has two different arguments for serviceEndpoint and masterKey, and these parameters should be passed as such.

https://docs.microsoft.com/en-us/java/api/com.microsoft.azure.documentdb._document_client.documentclient#com_microsoft_azure_documentdb__document_client_DocumentClient_String_String_ConnectionPolicy_ConsistencyLevel_

Account key needs to be passed as a distinct parameter. Account key is not meant to be suffixed to the service endpoint.
@zhang-hua  Why are you suffixing the service endpoint with the account key?

**Comment by zhang-hua** [comment]
@moderakh , agree with you. This is one of the bug we just found in our code when parsing the connection string. The account key is not correctly filtered and passed to DocumentClient by mistake. But it might be safer to check if account key is passed in DocumentClient as endpoint since it did not raise any exception or warning for developer when they misused this constructor. The credential will be leaked in the log message.  I'll leave it to you to decide to close it or not.  :-)
