### ISSUE TITLE
Parameter names in DocumentClient class are wrong

### ISSUE THREAD

**Issue by dcremonini** [Azure/azure-documentdb-java#98]
Two names of input parameters of methods contained in the `DocumentClient` class are misleading.

**Example**
If the code calls the method
`public FeedResponse<Permission> readPermissions(String permissionLink, FeedOptions options)`
using
`readPermissions("/dbs/exampleDB/users/johndoe/permissions", options);`
the resulting call made to the back-end server is
"/dbs/exampleDB/users/johndoe/permissions/permissions"
which fails because the method internally concantenates "/permissions" to the end of `permissionLink`  parameter.

**Affected methods**
Library version: 1.15.2

`public FeedResponse<Permission> readPermissions(String permissionLink, FeedOptions options)`
should be
`public FeedResponse<Permission> readPermissions(String userLink, FeedOptions options)`
and
`public FeedResponse<Permission> queryPermissions(String permissionLink, SqlQuerySpec querySpec, FeedOptions options)`
should be
`public FeedResponse<Permission> queryPermissions(String userLink, SqlQuerySpec querySpec, FeedOptions options)`

**Comment by srinathnarayanan** [comment]
@dcremonini Thanks for pointing this out. We will fix our documentation in the next release.

**Comment by srinathnarayanan** [comment]
The latest version has the correctly named parameters.
