### ISSUE TITLE
paging is not working

### ISSUE THREAD

**Issue by kinfkong** [Azure/azure-documentdb-java#99]
In my case, there are 4 documents in the collection.
When I set the page size to 1 (expecting to fetch only 1 result), but the sdk always returns all the documents in the collection.
code pieces:
```
final FeedOptions feedOptions = new FeedOptions();

        if (paging != null && paging.getPageSize() != 0) {
            // enable paging
            feedOptions.setPageSize(paging.getPageSize());
            feedOptions.setRequestContinuation(paging.getRequestContinuation());
        }

        feedOptions.setEnableCrossPartitionQuery(true);

        FeedResponse<Document> q = documentDbFactory.getDocumentClient()
                .queryDocuments(collections.get(0).getSelfLink(),
                        sqlQuerySpec, feedOptions);

        Iterator<Document> it = q.getQueryIterator();
        final List<T> entities = new ArrayList<>();
        while(it.hasNext()) {
            Document d = it.next();
            final T entity = mappingDocumentDbConverter.read(domainClass, d);
            entities.add(entity);
        }
```
After digging into it, I found that it will send 4 api requests (each fetch 1 result) for all the pages.
please see the requests I captured:
![snip20180205_8](https://user-images.githubusercontent.com/1898931/35797251-0d91f12c-0a9a-11e8-8cea-1ffb570a3975.png)

**Comment by srinathnarayanan** [comment]
Hi @kinfkong this is the expected paging behavior. When you call it.next(), it makes the next API call to get the next document (since your page size is only 1). What is your scenario/ use case and what is the behavior you expect?

**Comment by kinfkong** [comment]
@srinathnarayanan thanks for your reply.
I read the sample, it.next() should be read the documents in that page, not calling the next API?
If the it.next() is calling the next API, then how to iterate the documents of the current fetched page?
Thanks.

**Comment by srinathnarayanan** [comment]
@kinfkong it.next() makes an API call to fetch the next page only after all the documents in the current page have been iterated over. Since you set page size to 1, each it.next() will have to make a new API call to fetch a new page (of size 1). If you have 8 documents and set page size to 2, there will be a total of 4 API calls when you keep iterating with it.next()

**Comment by srinathnarayanan** [comment]
I am closing this as the initial query has been addressed. Please feel free to reopen it if you have any followup. Thanks!
